# Multi-stage build for the kPlay Next.js app.
#
# The runtime stage ships only the standalone server produced by
# `output: 'standalone'` — no source, no dev dependencies, no npm install on
# the VPS.

# ---- deps -------------------------------------------------------------
FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---- build ------------------------------------------------------------
FROM node:24-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Nothing in this app reads env at build time (every page is force-dynamic and
# every route handler reads process.env per request), so no build args needed.
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ---- runtime ----------------------------------------------------------
FROM node:24-alpine AS runtime
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup -g 1001 -S nodejs && adduser -u 1001 -S nextjs -G nodejs

# Static assets are served by the standalone server from this exact path.
# (There is no public/ directory in this project; add a COPY for it here if
# one is ever introduced.)
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static

# The migration script runs through plain `node`, outside the standalone
# bundle, so it needs its own sources and the mongodb driver.
COPY --from=build --chown=nextjs:nodejs /app/lib ./lib
COPY --from=build --chown=nextjs:nodejs /app/scripts ./scripts

USER nextjs
EXPOSE 3000

# server.js is generated by the standalone output.
CMD ["node", "server.js"]
